os:
    - linux

language: python

python:
    - 3.7

sudo: required

branches:
only:
    - gh-pages
    - /.*/

cache: pip

# Builds Test
env:
    global:
        - USR_NAME="OlafFilies"
        - USR_EMAIL="Olaf.Filies@infineon.com"
    matrix:
        - PLATFORMIO_CI_SRC=examples/Read_Angle_Speed_Revolutions
        - PLATFORMIO_CI_SRC=examples/Read_Angle_Value_Processing
        - PLATFORMIO_CI_SRC=examples/Read_Multiple_Registers
        - PLATFORMIO_CI_SRC=examples/Read_Sensor_Type
        - PLATFORMIO_CI_SRC=examples/Read_Speed_Processing
        - PLATFORMIO_CI_SRC=examples/Read_Test
        - PLATFORMIO_CI_SRC=examples/Read_Test_With_SlaveNumber
        - PLATFORMIO_CI_SRC=examples/Read_Write_Registers
        - PLATFORMIO_CI_SRC=examples/ReadAngleTest

install:
    - pip install -U platformio
    - platformio platform install -f infineonxmc
    - platformio platform install -f atmelavr

    script:
    - platformio ci --lib="." --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno --project-option="lib_deps=Wire"

    jobs:
    include:
        - stage: "Deploy"
    name: "GitHub Pages Deployment"
    if: tag IS present
        addons:
            apt:
                packages:
                - doxygen
                - graphviz
                sources:
                    - ubuntu-toolchain-r-test
        install:
            - git clone https://github.com/Infineon/InfineonDoxyGenerator.git --branch v.0.2.1
        script:
            - cd InfineonDoxyGenerator

            - python doxyifx.py html
            - python doxyifx.py release $GH_USER $GH_PASS_TOKEN

after_success:

