language: python
python:
    - "2.7"

sudo: required
        
branches:
  only:
    - master
    - version2

env:
    matrix:
        - PLATFORMIO_CI_SRC=examples/Read_Angle_Speed_Revolutions
        - PLATFORMIO_CI_SRC=examples/Read_Angle_Value_Processing
        - PLATFORMIO_CI_SRC=examples/Read_Multiple_Registers
        - PLATFORMIO_CI_SRC=examples/Read_Sensor_Type
        - PLATFORMIO_CI_SRC=examples/Read_Speed_Processing
        - PLATFORMIO_CI_SRC=examples/Read_Test
        - PLATFORMIO_CI_SRC=examples/Read_Test_With_SlaveNumber
        - PLATFORMIO_CI_SRC=examples/Read_Write_Registers
        - PLATFORMIO_CI_SRC=examples/ReadAngleTest

install:
    # build with stable core
    - pip install -U platformio
    - platformio platform install -f infineonxmc
    - platformio platform install -f atmelavr

script:
    - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit  --board=xmc4700_relax_kit --board=uno
